### ISSUE TITLE
running gene set analysis tutorial

### ISSUE THREAD

**Issue by shraddhapai** [inti/FORGE#2]
Hi Inti,
A typo report for the gene set analysis page. 
On this page:
https://github.com/inti/FORGE/wiki/Tutorials-4:-Gene-Set-Analyses

the call for gene-set analysis should read:
perl gsa.pl -gmt example/example.gmt -file example/exampl.gene_pvals -o example/example.out 

The current call references a gene pvalue file that is not in FORGE.zip.

**Comment by inti** [comment]
I appreciate it! Fixed now, cheers
